# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gon < Formula
  desc "Sign, notarize, and package macOS CLI applications written in any language."
  homepage ""
  version "0.0.2"
  depends_on :macos

  url "https://github.com/zerogate/gon/releases/download/v0.0.2/gon_macos.zip"
  sha256 "9fe2c40f507e356eca428c53f6454413953d8eb1fc76b62c906510101b270842"

  def install
    bin.install "gon"
  end

  on_arm do
    def caveats
      <<~EOS
        The darwin_arm64 architecture is not supported for the Gon
        formula at this time. The darwin_amd64 binary may work in compatibility
        mode, but it might not be fully supported.
      EOS
    end
  end
end
